### ISSUE TITLE
Other Plugin Compatibility

### ISSUE THREAD

**Issue by HollishKid** [OfficialDonut/SkVault#6] opened 2018-11-16 21:03 UTC
Hello,

I find some plugins to not properly recognize SkVault as an economy plugin.
My two examples are BetonQuest and MarketPlace which says:

`[BetonQuest] There is no economy plugin on the server!`

`[21:55:12 ERROR]: Error occurred while enabling MarketPlace v1.8.5 (Is it up to date?)
java.lang.UnsupportedOperationException: EconomyNameRequest
        at us._donut_.skvault.events.VaultEvent.verifyImplemented(VaultEvent.java:29) ~[?:?]
        at us._donut_.skvault.events.StringRequestEvent.getStringValue(StringRequestEvent.java:6) ~[?:?]
        at us._donut_.skvault.CustomEconomy.getName(CustomEconomy.java:63) ~[?:?]
        at xyz.rodeldev.marketplace.MarketPlace.hookWithPlugins(MarketPlace.java:165) ~[?:?]
        at xyz.rodeldev.marketplace.MarketPlace.onEnable(MarketPlace.java:65) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-f6a273b-a639ae4]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot.jar:git-Spigot-f6a273b-a639ae4]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-f6a273b-a639ae4]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:431) [spigot.jar:git-Spigot-f6a273b-a639ae4]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:345) [spigot.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:584) [spigot.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:546) [spigot.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:424) [spigot.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot.jar:git-Spigot-f6a273b-a639ae4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702) [spigot.jar:git-Spigot-f6a273b-a639ae4]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]`

Do you have any thoughts on this?
Thanks for your response!

**Comment by rodel77** [comment] 2018-11-17 06:30
Hey, I am the creator of the "other plugin", after testing a lot I think that the problem is just before the script loading phase in Skript

So after removing the "getName" call at the load event on my plugin gets fixed, is not a dependency loading problem but a Skript one loading scripts later even with is a softdepend

A possible fix is adding a name fallback like "SkVault" for plugins that call "getName" method on load

**Comment by OfficialDonut** [comment] 2020-03-22 01:57
Fixed in v2.0

**Closed as completed by OfficialDonut** 2020-03-22 01:57 UTC
